export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const GET_ARTICLE_DETAIL = "GET_ARTICLE_DETAIL";

export const IS_PLAYING_MUSIC = "IS_PLAYING_MUSIC";

export const CURRENT_MUSIC_ID = "CURRENT_MUSIC_ID";
